"""added email to user

Revision ID: 9570f27c2508
Revises: 166855700613
Create Date: 2022-04-09 18:49:46.755986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9570f27c2508'
down_revision = '166855700613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
